{ config, modulesPath, pkgs, lib, nixos-lima,... }:
{
    #
    # This is a sample configuration module for a NixOS Lima VM
    #
    imports = [
      (modulesPath + "/profiles/qemu-guest.nix")
      # The `lima` module sets up systemd services to support LimaVM
      nixos-lima.nixosModules.lima
    ];

    # system mounts
    # These settings match the image file generated by the NixOS Lima VM image generator
    fileSystems."/boot" = {
        device = lib.mkForce "/dev/vda1";  # /dev/disk/by-label/ESP
        fsType = "vfat";
    };
    fileSystems."/" = {
        device = "/dev/disk/by-label/nixos";
        autoResize = true;
        fsType = "ext4";
        options = [ "noatime" "nodiratime" "discard" ];
    };

    # misc
    boot.kernelPackages = pkgs.linuxPackages_latest;

    # The usual warnings about changing `stateVersion` apply. Make sure to find and read them
    # before changing this value.
    system.stateVersion = "25.11";
}
